### PR TITLE
Use autoprefixer for vendor prefixed properties

### PR DESCRIPTION
**Pull request by stream7**
I think we should update this best practice. See also http://css-tricks.com/autoprefixer/

Autoprefixer removes completely the concept of vendor prefixes from your codebase and also reduces the amount of code and code maintenance.

### CODE REVIEW

**Comment by inkel** [comment]
@stream7 interesting. Does `autoprefixer` works by parsing the generated CSS and then adding the vendor prefixes?

**Comment by stream7** [comment]
@inkel yes, it uses the caniuse database. You can read more at the [repo](https://github.com/postcss/autoprefixer)

**Comment by inkel** [comment]
Nice! :smiley_cat:

**Comment by stream7** [comment]
hey @sborrazas could you please merge this? I don't have access.

**Comment by sborrazas** [comment]
@stream7 Nice! :smiley:

**Comment by stream7** [comment]
@sborrazas :+1:

**Pull request merged**
